### ISSUE TITLE
could not find Ecto.Adapters.Postgres.Connection

### ISSUE THREAD

**Issue by arthurcolle** [phoenixframework/phoenix#1489]
Hi, with a brand new Phoenix project I am experiencing an error where the app is unable to find the Ecto.Adapters.Postgres.Connection module. I was able to build and compile (and run) a Phoenix app yesterday so I suspect that this could be a transient issue but that seems very strange to me.

I tried to clean ecto and rebuild only that dependency but it did not solve the issue.

I am on Windows 10 so I suspect that's the *issue* but that doesn't solve the problem. 

elixir-lang/ecto issue for reference: https://github.com/elixir-lang/ecto/issues/1211

```
C:\Users\arthu\Code\elixir\phoenix>mix phoenix.new holly
* creating holly/config/config.exs
* creating holly/config/dev.exs
* creating holly/config/prod.exs
* creating holly/config/prod.secret.exs
* creating holly/config/test.exs
* creating holly/lib/holly.ex
* creating holly/lib/holly/endpoint.ex
* creating holly/test/views/error_view_test.exs
* creating holly/test/support/conn_case.ex
* creating holly/test/support/channel_case.ex
* creating holly/test/test_helper.exs
* creating holly/web/channels/user_socket.ex
* creating holly/web/router.ex
* creating holly/web/views/error_view.ex
* creating holly/web/web.ex
* creating holly/mix.exs
* creating holly/README.md
* creating holly/web/gettext.ex
* creating holly/priv/gettext/errors.pot
* creating holly/priv/gettext/en/LC_MESSAGES/errors.po
* creating holly/web/views/error_helpers.ex
* creating holly/lib/holly/repo.ex
* creating holly/test/support/model_case.ex
* creating holly/priv/repo/seeds.exs
* creating holly/.gitignore
* creating holly/brunch-config.js
* creating holly/package.json
* creating holly/web/static/css/app.css
* creating holly/web/static/js/app.js
* creating holly/web/static/js/socket.js
* creating holly/web/static/assets/robots.txt
* creating holly/web/static/assets/images/phoenix.png
* creating holly/web/static/assets/favicon.ico
* creating holly/test/controllers/page_controller_test.exs
* creating holly/test/views/layout_view_test.exs
* creating holly/test/views/page_view_test.exs
* creating holly/web/controllers/page_controller.ex
* creating holly/web/templates/layout/app.html.eex
* creating holly/web/templates/page/index.html.eex
* creating holly/web/views/layout_view.ex
* creating holly/web/views/page_view.ex

Fetch and install dependencies? [Yn] Y
* running mix deps.get
* running npm install && node node_modules/brunch/bin/brunch build
npm WARN package.json @ No license field.
npm WARN optional dep failed, continuing fsevents@1.0.6
-
-

|
21 Jan 19:55:57 - error: Compiling of web\static\js\socket.js failed. Couldn't find preset "es2015" relative to directory "web\\static\\js" ; Compiling of web\static\js\app.js failed. Couldn't find preset "es2015" relative to directory "web\\static\\js"

We are all set! Run your Phoenix application:

    $ cd holly
    $ mix phoenix.server

You can also run your app inside IEx (Interactive Elixir) as:

    $ iex -S mix phoenix.server

Before moving on, configure your database in config/dev.exs and run:

    $ mix ecto.create


C:\Users\arthu\Code\elixir\phoenix>cd holly

C:\Users\arthu\Code\elixir\phoenix\holly>npm install --save-dev babel-preset-es2015
npm WARN package.json @ No license field.
babel-preset-es2015@6.3.13 node_modules\babel-preset-es2015
├── babel-plugin-transform-es2015-typeof-symbol@6.4.3 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-block-scoped-functions@6.3.13 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-template-literals@6.3.13 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-shorthand-properties@6.3.13 (babel-types@6.4.5, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-object-super@6.4.0 (babel-helper-replace-supers@6.3.13, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-literals@6.3.13 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-destructuring@6.4.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-arrow-functions@6.4.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-classes@6.4.5 (babel-helper-replace-supers@6.3.13, babel-helper-optimise-call-expression@6.3.13, babel-messages@6.3.18, babel-helper-function-name@6.4.0, babel-helper-define-map@6.4.5, babel-template@6.3.13, babel-types@6.4.5, babel-traverse@6.4.5, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-for-of@6.3.13 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-spread@6.4.0 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-modules-commonjs@6.4.5 (babel-plugin-transform-strict-mode@6.3.13, babel-template@6.3.13, babel-types@6.4.5, babel-runtime@5.8.35)
├── babel-plugin-check-es2015-constants@6.3.13 (babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-unicode-regex@6.4.3 (regexpu-core@1.0.0, babel-helper-regex@6.3.13, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-function-name@6.4.0 (babel-types@6.4.5, babel-helper-function-name@6.4.0, babel-runtime@5.8.35)
├── babel-plugin-transform-regenerator@6.4.4 (babel-plugin-syntax-async-functions@6.3.13, private@0.1.6, babylon@6.4.5, babel-types@6.4.5, babel-traverse@6.4.5, babel-core@6.4.5, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-parameters@6.4.5 (babel-helper-get-function-arity@6.3.13, babel-helper-call-delegate@6.3.13, babel-template@6.3.13, babel-types@6.4.5, babel-traverse@6.4.5, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-sticky-regex@6.3.13 (babel-helper-regex@6.3.13, babel-types@6.4.5, babel-runtime@5.8.35)
├── babel-plugin-transform-es2015-block-scoping@6.4.0 (babel-template@6.3.13, babel-types@6.4.5, babel-traverse@6.4.5, lodash@3.10.1, babel-runtime@5.8.35)
└── babel-plugin-transform-es2015-computed-properties@6.4.0 (babel-template@6.3.13, babel-helper-define-map@6.4.5, babel-runtime@5.8.35)

C:\Users\arthu\Code\elixir\phoenix\holly>
C:\Users\arthu\Code\elixir\phoenix\holly>
C:\Users\arthu\Code\elixir\phoenix\holly>mix phoenix.server
==> connection
Compiled lib/connection.ex
Generated connection app
==> fs (compile)
Compiled src/sys/fsevents.erl
Compiled src/sys/inotifywait.erl
Compiled src/sys/inotifywait_win32.erl
Compiled src/fs_sup.erl
Compiled src/fs_event_bridge.erl
Compiled src/fs_app.erl
Compiled src/fs_server.erl
Compiled src/fs.erl
==> gettext
Compiled src/gettext_po_parser.yrl
Compiled src/gettext_po_parser.erl
Compiled lib/gettext/interpolation.ex
Compiled lib/gettext/extractor_agent.ex
Compiled lib/gettext/po/translation.ex
Compiled lib/gettext/po/plural_translation.ex
Compiled lib/gettext/po/exceptions.ex
Compiled lib/gettext/fuzzy.ex
Compiled lib/gettext.ex
Compiled lib/gettext/po/parser.ex
Compiled lib/mix/tasks/gettext.extract.ex
Compiled lib/mix/tasks/compile.gettext.ex
Compiled lib/gettext/po/translations.ex
Compiled lib/gettext/po/tokenizer.ex
Compiled lib/gettext/compiler.ex
Compiled lib/gettext/merger.ex
Compiled lib/gettext/extractor.ex
Compiled lib/mix/tasks/gettext.merge.ex
Compiled lib/gettext/po.ex
Compiled lib/gettext/plural.ex
Generated gettext app
==> ranch (compile)
Compiled src/ranch_transport.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_protocol.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_ssl.erl
Compiled src/ranch_app.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch.erl
==> poolboy (compile)
Compiled src/poolboy_sup.erl
Compiled src/poolboy_worker.erl
Compiled src/poolboy.erl
==> decimal
Compiled lib/decimal.ex
Generated decimal app
==> poison
Compiled lib/poison.ex
Compiled lib/poison/parser.ex
Compiled lib/poison/decoder.ex
Compiled lib/poison/encoder.ex
Generated poison app
==> backoff (compile)
src/backoff.erl:115: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
src/backoff.erl:116: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
Compiled src/backoff.erl
==> db_connection
Compiled lib/db_connection/app.ex
Compiled lib/db_connection/error.ex
Compiled lib/db_connection/ownership/owner_supervisor.ex
Compiled lib/db_connection/log_entry.ex
Compiled lib/db_connection/ownership/pool.ex
Compiled lib/db_connection/ownership/pool_supervisor.ex
Compiled lib/db_connection/pool.ex
Compiled lib/db_connection/poolboy/worker.ex
Compiled lib/db_connection/ownership.ex
Compiled lib/db_connection/poolboy.ex
Compiled lib/db_connection/ownership/owner.ex
Compiled lib/db_connection/ownership/manager.ex
Compiled lib/db_connection/sojourn/broker.ex
Compiled lib/db_connection/sojourn/pool.ex
Compiled lib/db_connection/sojourn/supervisor.ex
Compiled lib/db_connection/sojourn.ex
Compiled lib/db_connection/sojourn/timeout.ex
Compiled lib/db_connection/query.ex
Compiled lib/db_connection/watcher.ex
Compiled lib/db_connection/sojourn/starter.ex
Compiled lib/db_connection/task.ex
Compiled lib/db_connection/connection.ex
Compiled lib/db_connection.ex
Generated db_connection app
==> cowlib (compile)
Compiled src/cow_spdy.erl
Compiled src/cow_multipart.erl
Compiled src/cow_qs.erl
Compiled src/cow_http_te.erl
Compiled src/cow_http_hd.erl
Compiled src/cow_date.erl
Compiled src/cow_http.erl
Compiled src/cow_cookie.erl
Compiled src/cow_mimetypes.erl
==> cowboy (compile)
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_websocket_handler.erl
Compiled src/cowboy_static.erl
Compiled src/cowboy_spdy.erl
Compiled src/cowboy_websocket.erl
Compiled src/cowboy_router.erl
Compiled src/cowboy_protocol.erl
Compiled src/cowboy_loop_handler.erl
Compiled src/cowboy_http_handler.erl
Compiled src/cowboy_rest.erl
Compiled src/cowboy_handler.erl
Compiled src/cowboy_clock.erl
Compiled src/cowboy_bstr.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy.erl
Compiled src/cowboy_http.erl
Compiled src/cowboy_req.erl
==> plug
Compiled lib/plug.ex
Compiled lib/plug/conn/status.ex
Compiled lib/plug/adapters/cowboy.ex
Compiled lib/plug/conn/adapter.ex
Compiled lib/plug/conn/unfetched.ex
Compiled lib/plug/builder.ex
Compiled lib/plug/conn/cookies.ex
Compiled lib/plug/conn/query.ex
Compiled lib/plug/conn/wrapper_error.ex
Compiled lib/plug/crypto.ex
Compiled lib/plug/crypto/message_verifier.ex
Compiled lib/plug/crypto/key_generator.ex
Compiled lib/plug/crypto/message_encryptor.ex
Compiled lib/plug/html.ex
Compiled lib/plug/error_handler.ex
Compiled lib/plug/conn/utils.ex
Compiled lib/plug/logger.ex
Compiled lib/plug/request_id.ex
Compiled lib/plug/exceptions.ex
Compiled lib/plug/session.ex
Compiled lib/plug/router.ex
Compiled lib/plug/supervisor.ex
Compiled lib/plug/session/store.ex
Compiled lib/plug/session/ets.ex
Compiled lib/plug/upload.ex
Compiled lib/plug/session/cookie.ex
Compiled lib/plug/head.ex
Compiled lib/plug/method_override.ex
Compiled lib/plug/router/utils.ex
Compiled lib/plug/adapters/translator.ex
Compiled lib/plug/test.ex
Compiled lib/plug/adapters/test/conn.ex
Compiled lib/plug/adapters/cowboy/handler.ex
Compiled lib/plug/adapters/cowboy/conn.ex
Compiled lib/plug/parsers.ex
Compiled lib/plug/parsers/urlencoded.ex
Compiled lib/plug/parsers/multipart.ex
Compiled lib/plug/parsers/json.ex
Compiled lib/plug/ssl.ex
Compiled lib/plug/conn.ex
Compiled lib/plug/static.ex
Compiled lib/plug/csrf_protection.ex
Compiled lib/plug/mime.ex
Compiled lib/plug/debugger.ex
Generated plug app
==> phoenix_html
Compiled lib/phoenix_html/format.ex
Compiled lib/phoenix_html.ex
Compiled lib/phoenix_html/engine.ex
Compiled lib/phoenix_html/tag.ex
Compiled lib/phoenix_html/link.ex
Compiled lib/phoenix_html/safe.ex
Compiled lib/phoenix_html/form_data.ex
Compiled lib/phoenix_html/form.ex
Generated phoenix_html app
==> phoenix
Compiled lib/mix/tasks/phoenix.gen.secret.ex
Compiled lib/mix/tasks/compile.phoenix.ex
Compiled lib/mix/tasks/phoenix.digest.ex
Compiled lib/mix/tasks/phoenix.gen.channel.ex
Compiled lib/mix/tasks/phoenix.gen.json.ex
Compiled lib/mix/tasks/phoenix.routes.ex
Compiled lib/mix/tasks/phoenix.server.ex
Compiled lib/phoenix.ex
Compiled lib/mix/phoenix.ex
Compiled lib/mix/tasks/phoenix.gen.html.ex
Compiled lib/phoenix/code_reloader.ex
Compiled lib/phoenix/code_reloader/proxy.ex
Compiled lib/mix/tasks/phoenix.gen.model.ex
Compiled lib/phoenix/config.ex
Compiled lib/phoenix/code_reloader/server.ex
Compiled lib/phoenix/controller/pipeline.ex
Compiled lib/phoenix/endpoint/handler.ex
Compiled lib/phoenix/endpoint/cowboy_websocket.ex
Compiled lib/phoenix/digester.ex
Compiled lib/phoenix/endpoint/watcher.ex
Compiled lib/phoenix/endpoint/cowboy_handler.ex
Compiled lib/phoenix/endpoint/server.ex
Compiled lib/phoenix/endpoint.ex
Compiled lib/phoenix/endpoint/adapter.ex
Compiled lib/phoenix/pubsub/gc.ex
Compiled lib/phoenix/pubsub/local_supervisor.ex
Compiled lib/phoenix/naming.ex
Compiled lib/phoenix/pubsub/pg2.ex
Compiled lib/phoenix/exceptions.ex
Compiled lib/phoenix/pubsub.ex
Compiled lib/phoenix/pubsub/pg2_server.ex
Compiled lib/phoenix/router/resource.ex
Compiled lib/phoenix/router/console_formatter.ex
Compiled lib/phoenix/router/scope.ex
Compiled lib/phoenix/router/route.ex
Compiled lib/phoenix/socket/message.ex
Compiled lib/phoenix/supervisor.ex
Compiled lib/phoenix/pubsub/local.ex
Compiled lib/phoenix/router.ex
Compiled lib/phoenix/channel/server.ex
Compiled lib/phoenix/socket.ex
Compiled lib/phoenix/channel.ex
Compiled lib/phoenix/endpoint/instrument.ex
Compiled lib/phoenix/template/engine.ex
Compiled lib/phoenix/template/html.ex
Compiled lib/phoenix/router/helpers.ex
Compiled lib/phoenix/param.ex
Compiled lib/phoenix/template/exs_engine.ex
Compiled lib/phoenix/template/eex_engine.ex
Compiled lib/phoenix/template.ex
Compiled lib/phoenix/socket/transport.ex
Compiled lib/phoenix/token.ex
Compiled lib/phoenix/controller.ex
Compiled lib/phoenix/transports/serializer.ex
Compiled lib/phoenix/transports/long_poll_serializer.ex
Compiled lib/phoenix/transports/websocket_serializer.ex
Compiled lib/phoenix/endpoint/render_errors.ex
Compiled lib/phoenix/transports/long_poll.ex
Compiled lib/phoenix/controller/logger.ex
Compiled lib/phoenix/transports/websocket.ex
Compiled lib/phoenix/transports/long_poll_server.ex
Compiled lib/phoenix/test/channel_test.ex
Compiled lib/phoenix/view.ex
Compiled lib/phoenix/test/conn_test.ex
Generated phoenix app
==> phoenix_live_reload
Compiled lib/phoenix_live_reload/socket.ex
Compiled lib/phoenix_live_reload/channel.ex
Compiled lib/phoenix_live_reload/live_reloader.ex
Generated phoenix_live_reload app
==> postgrex
Compiled lib/postgrex/binary_extension.ex
Compiled lib/postgrex/binary_utils.ex
Compiled lib/postgrex/app.ex
Compiled lib/postgrex/extension.ex
Compiled lib/postgrex/error_code.ex
Compiled lib/postgrex/extensions/bool.ex
Compiled lib/postgrex/error.ex
Compiled lib/postgrex/extensions/date.ex
Compiled lib/postgrex/extensions/float4.ex
Compiled lib/postgrex/extensions/float8.ex
Compiled lib/postgrex/extensions/int4.ex
Compiled lib/postgrex/extensions/int2.ex
Compiled lib/postgrex/extensions/int8.ex
Compiled lib/postgrex/extensions/hstore.ex
Compiled lib/postgrex/extensions/interval.ex
Compiled lib/postgrex/builtins.ex
Compiled lib/postgrex/extensions/raw.ex
Compiled lib/postgrex/extensions/macaddr.ex
Compiled lib/postgrex/extensions/tid.ex
Compiled lib/postgrex/extensions/void.ex
Compiled lib/postgrex/extensions/uuid.ex
Compiled lib/postgrex/extensions/time.ex
Compiled lib/postgrex/extensions/timestamp.ex
Compiled lib/postgrex/result.ex
Compiled lib/postgrex/extensions/numeric.ex
Compiled lib/postgrex/type_info.ex
Compiled lib/postgrex/extensions/record.ex
Compiled lib/postgrex/extensions/range.ex
Compiled lib/postgrex.ex
Compiled lib/postgrex/parameters.ex
Compiled lib/postgrex/extensions/oid.ex
Compiled lib/postgrex/extensions/json.ex
Compiled lib/postgrex/extensions/network.ex
Compiled lib/postgrex/notifications.ex
Compiled lib/postgrex/extensions/array.ex
Compiled lib/postgrex/type_server.ex
Compiled lib/postgrex/utils.ex
Compiled lib/postgrex/query.ex
Compiled lib/postgrex/types.ex
Compiled lib/postgrex/messages.ex
Compiled lib/postgrex/protocol.ex
Generated postgrex app
==> ecto
Compiled lib/ecto/adapter/transaction.ex
Compiled lib/ecto/adapter/storage.ex
Compiled lib/ecto/adapter/migration.ex
Compiled lib/ecto/adapters/postgres/datetime.ex
Compiled lib/ecto/adapters/mysql/connection.ex
Compiled lib/ecto/adapters/connection.ex
Compiled lib/ecto/adapter.ex
Compiled lib/ecto/adapters/postgres/connection.ex
Compiled lib/ecto/application.ex
Compiled lib/ecto/adapters/sql/query.ex
Compiled lib/ecto/data_type.ex
Compiled lib/ecto/migration/supervisor.ex
Compiled lib/ecto/model.ex
Compiled lib/ecto/model/optimistic_lock.ex
Compiled lib/ecto/model/callbacks.ex
Compiled lib/ecto/migrator.ex
Compiled lib/ecto/migration/runner.ex
Compiled lib/ecto/pools/sojourn_broker/codel.ex
Compiled lib/ecto/migration.ex
Compiled lib/ecto/pool.ex
Compiled lib/ecto/pools/sojourn_broker/timeout.ex
Compiled lib/ecto/pools/sojourn_broker.ex
Compiled lib/ecto/pools/poolboy.ex
Compiled lib/ecto/poison.ex
Compiled lib/ecto/pools/poolboy/worker.ex
Compiled lib/ecto/query/api.ex
Compiled lib/ecto/query/builder/distinct.ex
Compiled lib/ecto/query/builder/group_by.ex
Compiled lib/ecto/pools/sojourn_broker/worker.ex
Compiled lib/ecto/query/builder/from.ex
Compiled lib/ecto/query/builder/lock.ex
Compiled lib/ecto/query/builder/filter.ex
Compiled lib/ecto/query/builder/limit_offset.ex
Compiled lib/ecto/log_entry.ex
Compiled lib/ecto/adapters/sql/sandbox.ex
Compiled lib/ecto/adapters/sql.ex
Compiled lib/ecto/query.ex
Compiled lib/ecto/query/builder/join.ex
Compiled lib/ecto/query/builder/order_by.ex
Compiled lib/ecto/query/builder/select.ex
Compiled lib/ecto/query/builder/preload.ex
Compiled lib/ecto/exceptions.ex
Compiled lib/ecto.ex
Compiled lib/ecto/query/builder/update.ex
Compiled lib/ecto/adapters/postgres.ex
Compiled lib/ecto/query/builder.ex
Compiled lib/ecto/adapters/mysql.ex
Compiled lib/ecto/changeset/relation.ex
Compiled lib/ecto/query/inspect.ex
Compiled lib/ecto/repo/assoc.ex
Compiled lib/ecto/embedded.ex
Compiled lib/ecto/repo.ex
Compiled lib/ecto/repo/supervisor.ex
Compiled lib/ecto/storage.ex
Compiled lib/ecto/repo/preloader.ex
Compiled lib/ecto/queryable.ex
Compiled lib/ecto/query/planner.ex
Compiled lib/mix/ecto.ex
Compiled lib/mix/tasks/ecto.rollback.ex
Compiled lib/mix/tasks/ecto.migrate.ex
Compiled lib/mix/tasks/ecto.drop.ex
Compiled lib/mix/tasks/ecto.gen.migration.ex
Compiled lib/mix/tasks/ecto.gen.repo.ex
Compiled lib/mix/tasks/ecto.create.ex
Compiled lib/ecto/repo/schema.ex
Compiled lib/ecto/type.ex
Compiled lib/ecto/repo/queryable.ex
Compiled lib/ecto/schema.ex
Compiled lib/ecto/uuid.ex
Compiled lib/ecto/association.ex
Compiled lib/ecto/changeset.ex
Compiled lib/ecto/migration/schema_migration.ex
Compiled lib/ecto/date_time.ex
Generated ecto app
==> phoenix_ecto
Compiled lib/phoenix_ecto.ex
Compiled lib/phoenix_ecto/json.ex
Compiled lib/phoenix_ecto/plug.ex
Compiled lib/phoenix_ecto/html.ex
Generated phoenix_ecto app
==> holly
Compiled web/channels/user_socket.ex
Compiled lib/holly.ex
Compiled web/views/error_helpers.ex
Compiled web/web.ex
Compiled web/gettext.ex
Compiled lib/holly/repo.ex
Compiled web/views/error_view.ex
Compiled web/views/page_view.ex
Compiled web/controllers/page_controller.ex
Compiled web/router.ex
Compiled web/views/layout_view.ex
Compiled lib/holly/endpoint.ex
Generated holly app
Consolidated Phoenix.Param
Consolidated Ecto.DataType
Consolidated Poison.Decoder
Consolidated Plug.Exception
Consolidated Phoenix.HTML.Safe
Consolidated Phoenix.HTML.FormData
Consolidated DBConnection.Query
Consolidated Ecto.Queryable
Consolidated Poison.Encoder
Consolidated List.Chars
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
[info] Running Holly.Endpoint with Cowboy using http on port 4000
[info] Application holly exited: Holly.start(:normal, []) returned an error: shutdown: failed to start child: Holly.Repo
    ** (EXIT) shutdown: failed to start child: Ecto.Adapters.Postgres
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not find Ecto.Adapters.Postgres.Connection.

Please verify you have added :postgrex as a dependency:

    {:postgrex, ">= 0.0.0"}

And remember to recompile Ecto afterwards by cleaning the current build:

    mix deps.clean ecto

                (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.start_link/4
                (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:326: :supervisor.start_children/3
                (stdlib) supervisor.erl:292: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application holly: Holly.start(:normal, []) returned an error: shutdown: failed to start child: Holly.Repo
    ** (EXIT) shutdown: failed to start child: Ecto.Adapters.Postgres
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not find Ecto.Adapters.Postgres.Connection.

Please verify you have added :postgrex as a dependency:

    {:postgrex, ">= 0.0.0"}

And remember to recompile Ecto afterwards by cleaning the current build:

    mix deps.clean ecto

                (ecto) lib/ecto/adapters/sql.ex:420: Ecto.Adapters.SQL.start_link/4
                (stdlib) supervisor.erl:343: :supervisor.do_start_child/2
                (stdlib) supervisor.erl:326: :supervisor.start_children/3
                (stdlib) supervisor.erl:292: :supervisor.init_children/2
                (stdlib) gen_server.erl:328: :gen_server.init_it/6
                (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

C:\Users\arthu\Code\elixir\phoenix\holly>
```

**Comment by StevenNunez** [comment]
I got this too! In the mean time, change your requirement in you mix.exs to `{:postgrex, "0.11.0"}`

**Comment by mfeckie** [comment]
Version that fixes this (currently) is `{:postgrex, "0.10.0"}`

**Comment by arthurcolle** [comment]
dope, you guys are great. Guess the phoenix default config should be changed. Is 0.11 like a dev branch or something?

**Comment by morenoh149** [comment]
related https://github.com/phoenixframework/phoenix_guides/issues/463

**Comment by arthurcolle** [comment]
postgrex 0.10 works as desired, allows `mix phoenix.server` to start
postgrex 0.11 fails in the same way.

**Comment by chrismccord** [comment]
We need a new Ecto release with a bumped postgrex requirement. The fix for now is to pin postgrex  at 0.10.0:

    {:postgrex, "0.10.0"}

// @josevalim 

We'll have this taken care of soon. Thanks!

**Comment by sorentwo** [comment]
No, there isn't any Node style "odd numbers are experimental" versioning going on. There are just a lot of changes going into Ecto to prepare for 2.0, and Postgrex happens to be pre 1.0.

**Comment by whito** [comment]
Wow... thanks guys for being on top of this!

**Comment by josevalim** [comment]
Done. Ecto 1.1.2 is out with proper deps.

**Comment by chrismccord** [comment]
❤️❤️❤️❤️❤️

**Comment by princemaple** [comment]
anyone still getting `ecto 1.1.1` rather than `1.1.2` with default phoenix deps?

```elixir
  defp deps do
    [{:phoenix, "~> 1.1.3"},
     {:phoenix_ecto, "~> 2.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.3"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:cowboy, "~> 1.0"}]
  end
```

This, when `mix deps.get`, still gives me `ecto 1.1.1` and `postgrex 0.11.0`, which don't fit together.

**Comment by josevalim** [comment]
"mix deps.update ecto" should fix it!

On Friday, January 22, 2016, Po Chen <notifications@github.com> wrote:

> anyone still getting ecto 1.1.1 rather than 1.1.2 with default phoenix
> deps?
>
>   defp deps do
>     [{:phoenix, "~> 1.1.3"},
>      {:phoenix_ecto, "~> 2.0"},
>      {:postgrex, ">= 0.0.0"},
>      {:phoenix_html, "~> 2.3"},
>      {:phoenix_live_reload, "~> 1.0", only: :dev},
>      {:gettext, "~> 0.9"},
>      {:cowboy, "~> 1.0"}]
>   end
>
> This, when mix deps.get, still gives me ecto 1.1.1 and postgrex 0.11.0,
> which don't fit together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phoenixframework/phoenix/issues/1489#issuecomment-173896803>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by princemaple** [comment]
@josevalim I forgot to mention that I removed `mix.lock` prior to running `mix deps.get`, and it still got me `ecto 1.1.1`, any ideas?

**Comment by josevalim** [comment]
It is fixed for good now then. :) Thanks for the report!

**Comment by princemaple** [comment]
@josevalim I can confirm that it's fixed now. Was the reason the `1.1.2` release didn't get picked up that the `postgrex >= 0.0.0` was a main dependency and mix prioritized `postgrex`'s version?

**Comment by josevalim** [comment]
Yes, exactly. it is completely ordering based. Shuffling the deps around would give ecto higher priority. :)

**Comment by arthurcolle** [comment]
@josevalim awesome sauce, thanks for the help fellas. really speaks to the ex/phx community. <3

**Comment by graeme-defty** [comment]
This is all very nice, but would someone care to summarise for someone who does not yet quite grasp the magic incantations ... what do I actually have to DO?

My deps look like this:

`  defp deps do
    [{:phoenix, "~> 1.1.4"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_ecto, "~> 2.0"},
     {:phoenix_html, "~> 2.4"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.9"},
     {:comeonin, "~> 2.4"},
     {:cowboy, "~> 1.0"}]
  end
`

Thanks all.

**Comment by graeme-defty** [comment]
Sorry, I realise that doing `mix deps.update ecto` will fix the problem once, but how do I reorder my dependencies so that it does not go wrong next time?

... or is that it fixed for good?

**Comment by nubunto** [comment]
Having trouble with this with Ecto 2.1.4, Elixir 1.4.4, and Postgrex 0.13.3

```
defp deps do
    [{:postgrex, "~> 0.13"},
     {:ecto, "~> 2.1"}]
  end
```

```
λ ~/projects/gitlab/elixir-backends/apps/core/ master* mix deps.get
Running dependency resolution...
Dependency resolution completed:
  connection 1.0.4
  db_connection 1.1.2
  decimal 1.3.1
  ecto 2.1.4
  poolboy 1.5.1
  postgrex 0.13.3
All dependencies up to date
```

```
λ ~/projects/gitlab/elixir-backends/apps/core/ master* mix ecto.create

21:50:26.410 [error] Task #PID<0.159.0> started from #PID<0.70.0> terminating
** (UndefinedFunctionError) function Ecto.Adapters.Postgres.Connection.execute/4 is undefined (module Ecto.Adapters.Postgres.Connection is not available)
    Ecto.Adapters.Postgres.Connection.execute(#PID<0.160.0>, "CREATE DATABASE \"ecto_simple\" ENCODING 'UTF8'", [], [backoff_type: :stop, pool: DBConnection.Connection, database: "template1", otp_app: :core, repo: Core.Repo, adapter: Ecto.Adapters.Postgres, username: "postgres", password: "postgres"])
    lib/ecto/adapters/postgres.ex:226: anonymous fn/2 in Ecto.Adapters.Postgres.run_query/2
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<5.64847193/0 in Ecto.Adapters.Postgres.run_query/2>
    Args: []
** (Mix) The database for Core.Repo couldn't be created: an exception was raised:
    ** (UndefinedFunctionError) function Ecto.Adapters.Postgres.Connection.execute/4 is undefined (module Ecto.Adapters.Postgres.Connection is not available)
        Ecto.Adapters.Postgres.Connection.execute(#PID<0.160.0>, "CREATE DATABASE \"ecto_simple\" ENCODING 'UTF8'", [], [backoff_type: :stop, pool: DBConnection.Connection, database: "template1", otp_app: :core, repo: Core.Repo, adapter: Ecto.Adapters.Postgres, username: "postgres", password: "postgres"])
        lib/ecto/adapters/postgres.ex:226: anonymous fn/2 in Ecto.Adapters.Postgres.run_query/2
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by bigardone** [comment]
Hi! Same issue here
https://github.com/elixir-ecto/ecto/issues/1211#issuecomment-332648837
