### ISSUE TITLE
Cannot find module "phoenix_html" from "web/static/js/app"

### ISSUE THREAD

**Issue by supernova23** [phoenixframework/phoenix#1529]
i just generated a new application (phoenix v1.1.4) but when i run the server i see an error in my browser (javascript )
error 
`Cannot find module "phoenix_html" from "web/static/js/app"` in javascript console

**Comment by josevalim** [comment]
Please include phoenix version, elixir version, npm version and node version.

**Comment by supernova23** [comment]
phoenix 1.1.4
Elixir 1.2.0
node v5.5.0
npm 3.3.12

**Comment by josevalim** [comment]
Please run:

    mix deps.get
    npm install

Make sure you run the first one before the later. If it doesn't work, please paste your package.json. Is it a new application you just created?

**Comment by supernova23** [comment]
mix deps.get
`Running dependency resolution 
All dependencies up to date`
npm install
`npm WARN install Couldn't install optional dependency: Unsupported
npm WARN EPACKAGEJSON simple_chat No license field.`
it's an application (simple_chat) that i generated this morning using mix phoenix.new
package.json:
`{                                                                                                                                
  "repository": {
  },
  "dependencies": {
    "babel-brunch": "~6.0.0",
    "brunch": "~2.1.3",
    "clean-css-brunch": "~1.8.0",
    "css-brunch": "~1.7.0",
    "javascript-brunch": "~1.8.0",
    "uglify-js-brunch": "~1.7.0",
    "phoenix": "file:deps/phoenix",
    "phoenix_html": "file:deps/phoenix_html"
  }
}`

**Comment by josevalim** [comment]
That's so weird. can you please put it on github? I will take a look at it. Which OS are you using?

**Comment by supernova23** [comment]
os: windows 10
repo: https://github.com/supernova23/simple_chat
I just confirmed yhat versions before 1.1.4 do not have this problem

**Comment by josevalim** [comment]
Ah, please change "brunch": "~2.1.3" in your "package.json" by "brunch": "~2.2.3". that should fix it.

**Comment by josevalim** [comment]
Actually, I may be wrong. The solution may be to keep it as ~2.1.3 and run this:

    npm install brunch@2.1.3

See #1493.

**Comment by supernova23** [comment]
sorry but this doesn't solve the issue i will donwgrade to an older version until we solve this probleme think you for your time

**Comment by supernova23** [comment]
sorry but that doesn't solve the issue i will donwgrade to an older version until we solve this probleme think you for your time

**Comment by hurty** [comment]
Just in case someone stumbles on the same error, in your `brunch-config.js` make sure you have:

```
    npm: {
      enabled: true
    }
```

**Comment by Teddmab** [comment]
still facing the same issue

**Comment by unozerocode** [comment]
Has anyone seen this problem recently? It is showing up for us when trying to build a container, works find on the development PC but get the error inside the container.
`Version: webpack 4.41.5
s/app.js
Module not found: Error: Can't resolve 'phoenix_html' in '/app/assets/js'
`
Using exactly the Dockerfile from [HexDocs](https://hexdocs.pm/phoenix/releases.html#:~:text=Elixir%20releases%20work%20well%20with,based%20on%20the%20release%20artifacts.&text=At%20the%20end%2C%20you%20will,run%20as%20bin%2Fmy_app%20start%20.)
And tried updating to the elixir:1.10.0-alpine image to same effect.

**Comment by barttenbrinke** [comment]
run `mix deps.get` before you compile your assets. The js stuff is provided through the phoenix hex packages.
