### ISSUE TITLE
no route found for GET /unknown while running integration/endpoint_test

### ISSUE THREAD

**Issue by kenips** [phoenixframework/phoenix#1782]
Hey guys,

I'm running into this error sometimes while running `integration/endpoint_test`. It doesn't really affect the pass/failure of the tests but this would show up perhaps 70% of the time.

```
16:46:00.613 [debug] ** (Phoenix.Router.NoRouteError) no route found for GET /unknown (Phoenix.Integration.EndpointTest.Router)
    test/phoenix/integration/endpoint_test.exs:35: anonymous fn/1 in Phoenix.Integration.EndpointTest.Router.do_match/4
    test/phoenix/integration/endpoint_test.exs:16: Phoenix.Integration.EndpointTest.Router.plug_builder_call/2
    test/phoenix/integration/endpoint_test.exs:73: Phoenix.Integration.AdapterTest.DevEndpoint.phoenix_pipeline/1
    lib/plug/debugger.ex:93: Phoenix.Integration.AdapterTest.DevEndpoint."call (overridable 3)"/2
    test/phoenix/integration/endpoint_test.exs:73: Phoenix.Integration.AdapterTest.DevEndpoint."call (overridable 4)"/2
    test/phoenix/integration/endpoint_test.exs:73: Phoenix.Integration.AdapterTest.DevEndpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

I see that capture_log has been added to this test case for getting around race condition (sounds like I'm hitting one here). I'm not sure how it solves it though. Also puzzled at the discrepancy of the dev section vs the prod section here. Any insights? I'm running the test on current master.

**Comment by chrismccord** [comment]
Fixed. thanks!

**Comment by kenips** [comment]
Hey @chrismccord it's actually happening under the dev endpoint for me, so this change has no impact on the bug. I can still see it on latest master. Enclosing the call with capture_log doesn't silent the error for me however :'(
