### ISSUE TITLE
Response not being sent when using Plug.ErrorHandler

### ISSUE THREAD

**Issue by mitchellhenke** [phoenixframework/phoenix#1928]
Apologies in advance, as this issue has been difficult for me to investigate and I'm not 100% positive it's an issue with Phoenix, but I'm hoping to get to the bottom of it.

### Environment

* Elixir version: 1.3.2
* Phoenix version: 1.2.1
* Operating system: OS X 10.11.6

### Expected behavior
I have a somewhat simple Phoenix application that uses `Plug.ErrorHandler` to record an error when an exception is raised during the response.  It also uses the `Plug.Exception` protocol to set statuses on certain exceptions, and Phoenix's `ErrorView` to render the response.  I would also expect to be able to test with `assert_error_sent`.

### Actual behavior
A test using `assert_error_sent` for the exception and status specified will fail with:
```
expected 501 response but no response sent
```

I have an example reproduced [here](https://github.com/mitchellhenke/ErrorReportingEcto404).
While trying to get the test to pass, I found the test will pass as expected by making any one of these changes: [1](https://github.com/mitchellhenke/ErrorReportingEcto404/blob/0e9d647563e358ce817ea79e37696832ecd9592e/web/router.ex#L24-L27), [2](https://github.com/mitchellhenke/ErrorReportingEcto404/blob/0e9d647563e358ce817ea79e37696832ecd9592e/web/router.ex#L3-L4), [3](https://github.com/mitchellhenke/ErrorReportingEcto404/blob/0e9d647563e358ce817ea79e37696832ecd9592e/test/controllers/page_controller_test.exs#L6), [4](https://github.com/mitchellhenke/ErrorReportingEcto404/blob/0e9d647563e358ce817ea79e37696832ecd9592e/web/views/error_view.ex#L4-L7).

The above leads me to believe it's something between the way errors are handled, content types, and `Plug.ErrorHandler`, but I don't know enough to determine why.

**Comment by josevalim** [comment]
When you have an empty function as handle_errors, it seems you never send a response?

**Comment by mitchellhenke** [comment]
@josevalim if I override `handle_errors`, it doesn't send a response, which makes sense since the default is `Plug.Conn.send_resp(conn, conn.status, "Something went wrong")`.  The issue is if I override it, and do other things without sending a response, Phoenix will usually still send a response, but not in the above example.

**Comment by josevalim** [comment]
> The issue is if I override it, and do other things without sending a response, Phoenix will usually still send a response, but it doesn't in the above example.

Can you show me an example of this then? Because that sounds suspicious.

**Comment by mitchellhenke** [comment]
@josevalim I have a branch on the example repo here: https://github.com/mitchellhenke/ErrorReportingEcto404/tree/example-with-passing-test-and-non-empty-handle-errors

It uses Plug.ErrorHandler with an overridden handle_errors that does not send a response, and a route that raises an exception.  There is a test that calls that route showing that it does return with the expected status.  You would expect that it not return at all?

Feel free to ping me on IRC or Elixir slack (I'm mitchellhenke in those places as well) if you'd prefer being able to go back and forth quicker, as I'm a bit confused on the expected behavior for this and not sure if my current examples are helpful.

**Comment by josevalim** [comment]
Ok, it is a bug in Phoenix. The reason your branch passes is because you add the JSON header. This ensures it reaches the controller that raises the expected exception. If you don't add the header and remove assert_error_sent, you get the following error:

```
 ** (FunctionClauseError) no function clause matching in Phoenix.Template.HTML.encode_to_iodata!/1
       (phoenix) lib/phoenix/template/html.ex:12: Phoenix.Template.HTML.encode_to_iodata!(%{id: "INTERNAL_SERVER_ERROR", status: 500, title: "500 Internal server error"})
       (phoenix) lib/phoenix/controller.ex:642: Phoenix.Controller.do_render/4
       (phoenix) lib/phoenix/endpoint/render_errors.ex:58: Phoenix.Endpoint.RenderErrors.__catch__/5
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/page_controller_test.exs:7: (test)
```

so it seems assert_error_sent is swallowing the actual exception here. In a way that's what it is supposed to do, but it is doing a very bad job in reporting that. I will fix it. :)

**Comment by josevalim** [comment]
It should be fixed in master, thank you for the report!

**Comment by JoshSmith** [comment]
It looks like this is still an issue for me @josevalim and @mitchellhenke.

Here's a version with `1.3.0-dev` (that includes your change, José) and still has that failing test: https://github.com/JoshSmith/ErrorReportingEcto404

Happy to help how I can.
