### ISSUE TITLE
Compilation error in file installer/lib/phx_new/ecto.ex

### ISSUE THREAD

**Issue by eksperimental** [phoenixframework/phoenix#3906]
Running `mix test` generates a compilation error in one of the tests

### Environment

* Erlang version: Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 23)
* Phoenix version (mix deps): master
```
mix deps:
* ranch 1.7.1 (Hex package) (rebar3)
  locked at 1.7.1 (ranch) 451d8527
  ok
* telemetry 0.4.1 (Hex package) (rebar3)
  locked at 0.4.1 (telemetry) 4738382e
  ok
* jason 1.0.0 (Hex package) (mix)
  locked at 1.0.0 (jason) b96c400e
  ok
* phoenix_pubsub 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (phoenix_pubsub) c52d948c
  ok
* cowlib 2.8.0 (Hex package) (rebar3)
  locked at 2.8.0 (cowlib) 79f954a7
  ok
* cowboy 2.7.0 (Hex package) (rebar3)
  locked at 2.7.0 (cowboy) 04fd8c6a
  ok
* mime 1.3.1 (Hex package) (mix)
  locked at 1.3.1 (mime) 6cbe761d
  ok
* plug_crypto 1.1.2 (Hex package) (mix)
  locked at 1.1.2 (plug_crypto) 6b8b608f
  ok
* plug 1.10.3 (Hex package) (mix)
  locked at 1.10.3 (plug) 01f9037a
  ok
* plug_cowboy 2.3.0 (Hex package) (mix)
  locked at 2.3.0 (plug_cowboy) bc595a18
  ok
* phoenix_html 2.14.2 (Hex package) (mix)
  locked at 2.14.2 (phoenix_html) 58061c8d
  ok
```
* NodeJS version (node -v): 6.14.5
* NPM version (npm -v): v14.4.0
* Operating system: Arch Linux 64 bits

### Expected behavior
Not to print any errors

### Actual behavior
While all the tests pass, there is a compilation error that gets printed out.

```
...
warning: redefining module Phx.New.Web (current version loaded from /home/eksperimental/.asdf/installs/elixir/1.10.3-otp-23/.mix/archives/phx_new-1.5.3/phx_new-1.5.3/ebin/Elixir.Phx.New.Web.beam)
  installer/lib/phx_new/web.ex:1


== Compilation error in file installer/lib/phx_new/ecto.ex ==
** (File.Error) could not read file "/tmp/mix-local-installer-fetcher-4mz-PA/deps/phx_new/templates/phx_umbrella/apps/app_name/config/config.exs": no such file or directory
    (elixir 1.10.3) lib/file.ex:353: File.read!/1
    lib/phx_new/generator.ex:31: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/phx_new/generator.ex:27: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Phx.New.Generator.__before_compile__/1
    installer/lib/phx_new/ecto.ex:1: Phx.New.Ecto (module)
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:305: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
..........................................
14:00:13.166 [error] :force_ssl mismatch for Phoenix.Endpoint.SupervisorTest.ForceSslEndpoint.

Compile time configuration: [rewrite_on: [:x_forwarded_proto]]
Runtime configuration     : [hsts: true]

:force_ssl is a compile-time configuration, so setting
it at runtime has no effect. Therefore you must set it in your
config/prod.exs or similar (not in your config/releases.exs)
and make sure the value doesn't change.

................................................................................................................................................................................................................................................................................................................................................................................................................
14:00:18.095 [debug] HANDLED broadcast INCOMING ON foo:ok (Phoenix.Test.ChannelTest.Channel) in 23µs
  Parameters: %{"foo" => "bar"}
.........................................................................................................................................................................................................................................................................................

Finished in 25.6 seconds
17 doctests, 714 tests, 0 failures

Randomized with seed 194711
```

**Comment by eksperimental** [comment]
Additionally, docs cannot be generated due to the same error.

**Comment by josevalim** [comment]
You have an archive for phx_new installed and that's affecting Phoenix suite. Running ` mix archive.uninstall phx_new` should fix it. We should probably add some automatic verification for this and warn users upfront.

**Comment by eksperimental** [comment]
Thanks. Running `mix archive.uninstall phx_new` worked, but the commit didn't solve the issue.

**Comment by eksperimental** [comment]
Oh.. I see  the commit only runs in a test.

**Comment by josevalim** [comment]
@eksperimental ah, I see. Maybe we should move that line to the top of `phx_new` mix.exs file or similar execute before we run the docs command too.

**Comment by MaSven** [comment]
Yes this should be moved somewhere else. In the moment this breaks compilation also in other environments.

**Comment by MaSven** [comment]
Ups this was already resolved in https://github.com/phoenixframework/phoenix/commit/496627f2f7bbe92fc481bad81a59dd89d8205508

**Comment by eksperimental** [comment]
I have been hit by the same issue again, with the current Phoenix master.

```console
$ MIX_ENV=docs mix docs
Compiling 79 files (.ex)
warning: redefining module Mix.Tasks.Local.Phx (current version loaded from /home/eksperimental/.asdf/installs/elixir/1.12.3-otp-24/.mix/archives/phx_new-1.6.2/phx_new-1.6.2/ebin/Elixir.Mix.Tasks.Local.Phx.beam)
  installer/lib/mix/tasks/local.phx.ex:1

warning: redefining module Phx.New.Project (current version loaded from /home/eksperimental/.asdf/installs/elixir/1.12.3-otp-24/.mix/archives/phx_new-1.6.2/phx_new-1.6.2/ebin/Elixir.Phx.New.Project.beam)
  installer/lib/phx_new/project.ex:1

warning: redefining module Phx.New.Generator (current version loaded from /home/eksperimental/.asdf/installs/elixir/1.12.3-otp-24/.mix/archives/phx_new-1.6.2/phx_new-1.6.2/ebin/Elixir.Phx.New.Generator.beam)
  installer/lib/phx_new/generator.ex:1

warning: redefining module Phx.New.Mailer (current version loaded from /home/eksperimental/.asdf/installs/elixir/1.12.3-otp-24/.mix/archives/phx_new-1.6.2/phx_new-1.6.2/ebin/Elixir.Phx.New.Mailer.beam)
  installer/lib/phx_new/mailer.ex:1


== Compilation error in file installer/lib/phx_new/mailer.ex ==
** (File.Error) could not read file "/tmp/mix-local-installer-fetcher-g7QEDw/deps/phx_new/templates/phx_mailer/lib/app_name/mailer.ex": no such file or directory
    (elixir 1.12.3) lib/file.ex:355: File.read!/1
    (eex 1.12.3) lib/eex.ex:238: EEx.compile_file/2
    (phx_new 1.6.2) lib/phx_new/generator.ex:31: anonymous fn/4 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phx_new 1.6.2) lib/phx_new/generator.ex:27: anonymous fn/3 in Phx.New.Generator."MACRO-__before_compile__"/2
    (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phx_new 1.6.2) expanding macro: Phx.New.Generator.__before_compile__/1
    installer/lib/phx_new/mailer.ex:1: Phx.New.Mailer (module)

```
