### ISSUE TITLE
latest pheonix package can not be used in node.js

### ISSUE THREAD

**Issue by wangshijun** [phoenixframework/phoenix#4506]
### Environment

* Elixir version (elixir -v): Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): Not Applicable
* Operating system: MacOS

### Expected behavior

https://www.npmjs.com/package/phoenix can work in node.js on 1.5.x, it should work in node.js for 1.6 release.

### Actual behavior

but when 1.6.0 is out, the node.js runtime throws an error:

```
(node:2076) UnhandledPromiseRejectionWarning: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /usr/local/lib/node_modules/@abtnode/cli/node_modules/phoenix/package.json
```

**Comment by jamesvl** [comment]
I believe I'm having a similar issue when updating to Phoenix 1.6. An existing project that is still using brunch (it started back in the early Phoenix days and I haven't had a need to change to webpack) can no longer compile the Phoenix JS asset, when previously it did for 1.5.x.

### Environment
```
elixir          1.12.3-otp-24
erlang          24.1
nodejs          16.9.1
rebar           3.16.1
phoenix         1.6.0
```

npm package versions for Phoenix are

* phoenix_html@3.0.4 -> ./../deps/phoenix_html
* phoenix_live_view@0.16.4 -> ./../deps/phoenix_live_view
* phoenix@1.6.0 -> ./../deps/phoenix

The error message plus JS stack trace is

```
$LOGGY_STACKS=1 npm run deploy

> deploy
> brunch build --production

08:00:07 - error: Processing of js/app.js failed. Error: Could not load module 'phoenix' from '/ex/assets/js'. Possible solution: run `npm install`.
    at friendlyRequireError (/ex/assets/node_modules/deppack/lib/resolve.js:69:9)
    at /ex/assets/node_modules/deppack/lib/resolve.js:90:17
    at /ex/assets/node_modules/browser-resolve/index.js:265:24
    at /ex/assets/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/ex/assets/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/ex/assets/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/ex/assets/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/ex/assets/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /ex/assets/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (node:fs:198:21)
```

This above error occurs whether using `file` packages or installing the above directly from `npm`. I have verified that either symlinks or the npm package exists when I try either method of installing.


The first 3 lines of my `app.js` file are

```js
import "phoenix_html"

import {Socket} from "phoenix"
import {LiveSocket} from "phoenix_live_view"
```

**Comment by grossvogel** [comment]
I encountered this issue as well and was able to resolve it temporarily by adding a `require` key under `exports` in the `package.json` files for `phoenix` and `phoenix_live_view`. I'm not an expert in the Javascript module loading mechanisms, though, so I don't know if this even approaches being the "correct" fix for this...

`phoenix/package.json`
```diff
10c10,11
<     "import": "./priv/static/phoenix.esm.js"
---
>     "import": "./priv/static/phoenix.esm.js",
>     "require": "./priv/static/phoenix.min.js"
```

`phoenix_live_view/package.json`
```diff
11c11,12
<     "import": "./priv/static/phoenix_live_view.esm.js"
---
>     "import": "./priv/static/phoenix_live_view.esm.js",
>     "require": "./priv/static/phoenix_live_view.min.js"
```

**Comment by hubertlepicki** [comment]
I have prepared a PR (#4512) that you folks can try out: note, there are no pre-built commonjs files there so you'd have to check it out locally and run "mix assets.build" and then point your dependency in package.js to the path where it's checked out.

I also prepared a branch with these files pre-built if that's easier, in order to try it out you'd have to point your mix dependency to something like: 

`{:phoenix, github: "hubertlepicki/phoenix", branch: "bild_commonjs_module_with_built_module"}`

Can you try either of the methods and report if my PR fixes your issues?

**Comment by jamesvl** [comment]
Your prepared branch works for me. :tada: 

I was able to pull it down and run the brunch build without any issues or modifications.

**Comment by mcrumm** [comment]
This should be resolved on master. If you're able, please give it a try and report back, thanks!

// @wangshijun @jamesvl @grossvogel

**Comment by jamesvl** [comment]
@mcrumm Confirmed working for me on Phoenix master, as well.

**Comment by grossvogel** [comment]
@mcrumm `master` is working for me in webpack. My `mocha` tests are still failing with `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in .../node_modules/phoenix/package.json` but that may be something I can fix with `ts-node` config

**Comment by mcrumm** [comment]
@grossvogel Can you point at the `mc-cjs-require` branch and tell me whether or not that fixes the issue? See #4520 for more info

**Comment by grossvogel** [comment]
@mcrumm Yes, that does correct the problem in my test for `phoenix`... I'm seeing the same error from `...assets/node_modules/phoenix_live_view/package.json` now, but I guess it's probably just a matter of porting the same set of fixes once everybody's satisfied...

**Comment by mcrumm** [comment]
Thanks @grossvogel!

I merged #4521 and I am going to close this issue. @wangshijun please try master and re-open if the issue remains :)
