### ISSUE TITLE
1.6.0 breaking non-esm build pipelines

### ISSUE THREAD

**Issue by tornqvist** [phoenixframework/phoenix#4520]
### Environment

Node (Browserify)

### Expected behavior

Updating the package 1.5.0 -> 1.6.0 should not break current implementation.

### Actual behavior

Migrating to an ESM-only package (https://github.com/phoenixframework/phoenix/pull/4372) breaks all build pipelines not using ESM.

I see that the Phoenix framework have moved to ESM but there are a lot of other consumers out there, some still using CommonJS, whose build pipelines broke due to this change. This should have been a major update.

**Comment by mcrumm** [comment]
Hi @tornqvist! This should be fixed now on master. Can you try it out and report back? Thanks!

**Comment by tornqvist** [comment]
I missed that there already was a PR. However I'm still getting the error `Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /[…]/node_modules/phoenix/package.json` on master.

However, making this change to the `package.json` solves the issue:
```diff
 "exports": {
+    "require": "./priv/static/phoenix.cjs.js",
     "import": "./priv/static/phoenix.esm.js"
 },
```
